# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "node01"

  # special
  config.vm.network "private_network", ip: "10.0.15.21", virtualbox__intnet: true
  # config.vm.network "forwarded_port", guest: 80, host: 3001, host_ip: "10.0.15.21"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "4096"
    vb.cpus = 2
    vb.name = "node01"

    # exec cap: even if the machine works at 100%+ cpu, it won't affect the host device too much, causing it's overheat
    vb.customize ["modifyvm", :id, "--cpuexecutioncap", "50", "--nictype1", "virtio"]
  end

  config.vm.provision "shell", privileged: false, inline: <<-SHELL

    # prepare
    printf "\n10.0.15.10 k8s-master\n10.0.15.10 master\n10.0.15.21 node01\n10.0.15.22 node02\n" | sudo tee -a /etc/hosts
    sudo setenforce 0
    sudo sed -i --follow-symlinks 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/sysconfig/selinux
    sudo modprobe br_netfilter
    echo "br_netfilter" | sudo tee -a /etc/modules-load.d/br_netfilter.conf

    # todo:
    # the next command does not survive system restart
    echo '1' | sudo tee -a /proc/sys/net/bridge/bridge-nf-call-iptables

    sudo swapoff -a

    # install Docker
    sudo yum install -y yum-utils device-mapper-persistent-data lvm2
    sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    sudo yum install -y docker-ce

    sudo mkdir /etc/docker
sudo tee /etc/docker/daemon.json > /dev/null <<'EOF'
{
  "exec-opts": ["native.cgroupdriver=systemd"],
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "100m"
  },
  "storage-driver": "overlay2",
  "storage-opts": [
    "overlay2.override_kernel_check=true"
  ]
}
EOF

    # install kubernetes
sudo tee /etc/yum.repos.d/kubernetes.repo > /dev/null <<'EOF'
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
        https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
EOF
    sudo yum install -y kubelet kubeadm kubectl

    # start all
    sudo systemctl start docker
    sudo systemctl enable docker
    sudo systemctl start kubelet
    sudo systemctl enable kubelet
  SHELL
end
